services:
  spark-jupyter:
    build: .
    container_name: spark-jupyter
    networks:
      - spark-network
    ports:
      - "8888:8888"  # Puerto de Jupyter
      - "7077:7077"  # Puerto de Spark (Master)
    environment:
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS="notebook"
      - SPARK_MASTER=spark://spark-jupyter:7077
    volumes:
      - ./notebooks:/home/jupyter  # Opcional: Monta un volumen local para los notebooks
    restart: always

networks:
  spark-network:
    driver: bridge
